sequenceDiagram
    User->>Lambda: Request
    Lambda->>DDB: Request
    DDB->>Aurora: Request
    Aurora->>RDS: Request
    RDS-->>Aurora: Response
    Aurora-->>DDB: Response
    DDB-->>Lambda: Response
    Lambda-->>User: Response